import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Winery Wedding Timeline | CaliforniaWineryWeddings.com',
  description: 'Embeddable winery wedding day timeline — generated by CaliforniaWineryWeddings.com',
  robots: { index: false },
};

export default function EmbedLayout({ children }: { children: React.ReactNode }) {
  return children;
}
